export const projects = [
  {
    id: 'assignmentbuds',
    slug: 'assignmentbuds',
    title: 'AssignmentBuds',
    category: 'Web',
    description: 'A comprehensive academic writing service platform built with WordPress, providing students with professional essay writing, dissertation help, and assignment assistance.',
    longDescription: 'AssignmentBuds is a full-featured academic writing service platform that connects students with expert writers. The platform includes order management, payment processing, writer matching, and customer support systems.',
    stack: ['WordPress', 'PHP', 'MySQL', 'JavaScript', 'CSS', 'WooCommerce'],
    image: '/images/assignmentbuds.jpg',
    liveUrl: 'https://assignmentbuds.com/',
    githubUrl: null,
    problem: 'Students needed a reliable, user-friendly platform to access professional academic writing services with transparent pricing and quality guarantees.',
    solution: 'Developed a comprehensive WordPress-based platform with custom functionality for order management, writer assignment, payment processing, and customer communication.',
    keyFeatures: [
      'Order placement and management system',
      'Writer matching and assignment',
      'Secure payment processing',
      'Real-time order tracking',
      'Customer support integration',
      'Review and rating system',
    ],
    results: 'Successfully launched a professional academic writing service platform serving thousands of students with reliable, high-quality writing assistance.',
    screenshots: [
      '/images/assignmentbuds-1.jpg',
      '/images/assignmentbuds-2.jpg',
      '/images/assignmentbuds-3.jpg',
    ],
  },
  {
    id: 'nursfpxwriters',
    slug: 'nursfpxwriters',
    title: 'NursFPXWriters',
    category: 'Web',
    description: 'Specialized nursing assignment writing service platform built with WordPress, focusing on nursing students and healthcare professionals.',
    longDescription: 'NursFPXWriters is a niche academic writing platform specifically designed for nursing students. The platform offers specialized services for nursing assignments, case studies, and research papers with expert nursing writers.',
    stack: ['WordPress', 'PHP', 'MySQL', 'JavaScript', 'CSS', 'Custom Plugins'],
    image: '/images/nursfpxwriters.jpg',
    liveUrl: 'https://nursfpxwriters.com/',
    githubUrl: null,
    problem: 'Nursing students required a specialized platform with writers who understand healthcare terminology and nursing-specific requirements.',
    solution: 'Created a WordPress-based platform with custom features for nursing assignment services, including specialized writer profiles, healthcare-focused content, and nursing-specific templates.',
    keyFeatures: [
      'Specialized nursing assignment services',
      'Expert nursing writer profiles',
      'Healthcare-focused content management',
      'Nursing-specific templates and resources',
      'Secure order and payment system',
      '24/7 customer support',
    ],
    results: 'Established a trusted platform for nursing students to access specialized writing assistance from qualified healthcare professionals.',
    screenshots: [
      '/images/nursfpxwriters-1.jpg',
      '/images/nursfpxwriters-2.jpg',
      '/images/nursfpxwriters-3.jpg',
    ],
  },
  {
    id: 'writemynursing',
    slug: 'writemynursing',
    title: 'WriteMyNursing',
    category: 'Web',
    description: 'Professional nursing paper writing service platform developed with WordPress, offering comprehensive academic support for nursing students.',
    longDescription: 'WriteMyNursing is a dedicated platform for nursing students seeking professional writing assistance. The platform provides services for nursing papers, research projects, and academic assignments with a focus on healthcare education.',
    stack: ['WordPress', 'PHP', 'MySQL', 'JavaScript', 'CSS', 'WooCommerce'],
    image: '/images/writemynursing.jpg',
    liveUrl: 'https://writemynursing.com/',
    githubUrl: null,
    problem: 'Nursing students needed a reliable platform with writers experienced in healthcare and nursing education to help with complex assignments.',
    solution: 'Built a WordPress platform with custom functionality for nursing assignment services, including writer vetting, quality assurance, and specialized nursing content delivery.',
    keyFeatures: [
      'Nursing paper writing services',
      'Healthcare expert writer network',
      'Quality assurance and plagiarism checking',
      'Custom order management system',
      'Payment and billing integration',
      'Student dashboard and order tracking',
    ],
    results: 'Delivered a professional platform that helps nursing students achieve academic success with expert-written nursing papers and assignments.',
    screenshots: [
      '/images/writemynursing-1.jpg',
      '/images/writemynursing-2.jpg',
      '/images/writemynursing-3.jpg',
    ],
  },
  {
    id: 'study-nursfpxwriters',
    slug: 'study-nursfpxwriters',
    title: 'Study Portal - NursFPXWriters',
    category: 'Web',
    description: 'Custom-built study portal and learning management system using HTML, CSS, JavaScript, and PHP for nursing students.',
    longDescription: 'A custom-built study portal providing nursing students with access to study materials, resources, and learning tools. Built from scratch with vanilla technologies for optimal performance and customization.',
    stack: ['HTML5', 'CSS3', 'JavaScript', 'PHP', 'MySQL', 'jQuery'],
    image: '/images/study-portal.jpg',
    liveUrl: 'https://study.nursfpxwriters.com/',
    githubUrl: null,
    problem: 'Nursing students needed a dedicated study portal with custom functionality that couldn\'t be achieved with standard CMS platforms.',
    solution: 'Developed a custom study portal from scratch using HTML, CSS, JavaScript, and PHP, providing complete control over features, design, and user experience.',
    keyFeatures: [
      'Custom study material management',
      'User authentication and profiles',
      'Resource library and downloads',
      'Interactive learning tools',
      'Progress tracking system',
      'Responsive design and mobile support',
    ],
    results: 'Created a fully customized study portal that provides nursing students with a tailored learning experience and access to specialized resources.',
    screenshots: [
      '/images/study-portal-1.jpg',
      '/images/study-portal-2.jpg',
      '/images/study-portal-3.jpg',
    ],
  },
  {
    id: 'ecelinkup',
    slug: 'ecelinkup',
    title: 'EceLinkUp',
    category: 'Mobile',
    description: 'A mobile application that connects job providers with job seekers in the ECE staffing industry, enabling seamless job posting, candidate discovery, and streamlined matching through an intuitive mobile interface.',
    longDescription: 'EceLinkUp is a mobile application designed for the ECE staffing context, facilitating meaningful connections between employers and qualified candidates. The mobile platform streamlines the entire hiring workflow from job posting to candidate onboarding, providing a convenient and accessible solution for both job providers and job seekers.',
    stack: ['React Native', 'React', 'Node.js', 'Express', 'MongoDB', 'Mobile UI'],
    image: '/images/ecelinkup.jpg',
    liveUrl: 'https://ecelinkup.com',
    githubUrl: null,
    problem: 'The ECE staffing industry lacked a mobile platform for connecting job providers with qualified candidates, making it difficult to access opportunities on-the-go.',
    solution: 'Built a comprehensive mobile application with advanced search, verification systems, and streamlined onboarding workflows. Implemented role-based access control for job providers, candidates, and administrators with a mobile-first approach.',
    keyFeatures: [
      'Mobile app for iOS and Android platforms',
      'Job posting and management system',
      'Advanced candidate search and filtering',
      'Profile verification and credential management',
      'Application tracking and scheduling',
      'Admin dashboard for platform oversight',
      'Real-time notifications and updates',
      'Mobile-optimized user experience',
    ],
    results: 'Streamlined the hiring process for ECE staffing through mobile accessibility, enabling faster candidate discovery and improved matching between job providers and qualified professionals.',
    screenshots: [
      '/images/ecelinkup-1.jpg',
      '/images/ecelinkup-2.jpg',
      '/images/ecelinkup-3.jpg',
    ],
  },
  {
    id: 'gds-attendance',
    slug: 'global-digital-solutions-attendance',
    title: 'Global Digital Solutions — Attendance & HR Management Portal',
    category: 'Web',
    description: 'Internal portal for comprehensive attendance tracking and HR operations management. Built as part of my role at Global Digital Solution using React, Node.js, Express, PHP, and WordPress.',
    longDescription: 'A robust internal portal designed for Global Digital Solutions to manage employee attendance, shift tracking, and HR workflows. Developed using React, Node.js, Express, PHP, and WordPress. The system provides real-time attendance monitoring, comprehensive reporting, and role-based access control. Deployed on cloud platforms including Render, Vercel, and Hostinger for optimized performance and availability.',
    stack: ['React', 'Node.js', 'Express', 'PHP', 'WordPress', 'MySQL', 'MongoDB', 'HTML', 'CSS', 'JavaScript'],
    image: '/images/gds-attendance.jpg',
    liveUrl: 'https://ams.globaldigitsolutions.com/',
    githubUrl: null,
    problem: 'Manual attendance tracking and HR operations were time-consuming and prone to errors, requiring a centralized digital solution for efficient employee management.',
    solution: 'Developed a comprehensive HR management portal with automated attendance tracking, shift management, employee records, and detailed reporting capabilities. Built responsive frontends with HTML, CSS, and JavaScript while integrating RESTful APIs for dynamic data exchange.',
    keyFeatures: [
      'Real-time attendance tracking and clock-in/out system',
      'Shift management and scheduling',
      'Employee profile and records management',
      'Comprehensive HR workflows',
      'Advanced reporting and analytics',
      'Role-based access control (Admin, HR, Employee)',
      'Database management with SQL and MongoDB',
      'Cloud deployment on Render, Vercel, and Hostinger',
    ],
    results: 'Significantly improved HR efficiency with automated attendance tracking and streamlined employee management processes. Successfully deployed and maintained on cloud platforms for optimal performance.',
    screenshots: [
      '/images/gds-1.jpg',
      '/images/gds-2.jpg',
      '/images/gds-3.jpg',
    ],
  },
  {
    id: 'hike-connect',
    slug: 'hike-connect',
    title: 'Hike-Connect App',
    category: 'Mobile',
    description: 'Final Year Project (FYP) - A mobile application for organizing and joining hiking events, built with MERN stack and React Native. Enables users to create public, private, and featured hiking events while fostering community engagement.',
    longDescription: 'Hike-Connect is my Final Year Project (FYP) - an innovative mobile application that brings together outdoor enthusiasts and event organizers. The platform enables users to organize public, private, and featured hiking events, fostering community engagement. Built with React Native for a seamless mobile experience and MERN stack for robust backend services.',
    stack: ['React Native', 'React', 'Node.js', 'Express', 'MongoDB', 'Redux'],
    image: '/images/hike-connect.jpg',
    liveUrl: null,
    githubUrl: 'https://github.com/muhammadfasih/hike-connect',
    problem: 'Outdoor enthusiasts lacked a centralized mobile platform to discover hiking events and connect with like-minded individuals in their area.',
    solution: 'Developed a comprehensive mobile application with React Native featuring intuitive user interface, event management, user authentication, and real-time updates. Engineered backend services with Node.js and MongoDB for efficient event management and user interactions.',
    keyFeatures: [
      'Mobile app built with React Native for iOS and Android',
      'Create and organize public, private, and featured hiking events',
      'User profiles and social connections',
      'Location-based event search and discovery',
      'Event RSVP and attendance tracking',
      'Real-time notifications and updates',
      'Secure user authentication and event management',
    ],
    results: 'Successfully delivered a fully functional mobile application as Final Year Project, connecting outdoor enthusiasts and facilitating community building around hiking and outdoor activities.',
    screenshots: [
      '/images/hike-1.jpg',
      '/images/hike-2.jpg',
      '/images/hike-3.jpg',
    ],
  },
  {
    id: 'employee-activity-detector',
    slug: 'employee-activity-detector',
    title: 'Employee Activity Detector',
    category: 'Automation',
    description: 'Python-based idle detection system with MERN dashboard for monitoring and reporting employee activity.',
    longDescription: 'An intelligent employee activity monitoring system that tracks idle time, application usage, and generates comprehensive reports. The system includes a Python-based detection engine and a modern MERN stack dashboard for visualization and management.',
    stack: ['Python', 'React', 'Node.js', 'Express', 'MongoDB', 'Chart.js'],
    image: '/images/activity-detector.jpg',
    liveUrl: null,
    githubUrl: 'https://github.com/muhammadfasih/activity-detector',
    problem: 'Organizations needed a reliable way to monitor employee activity and productivity without being intrusive, with detailed logging and reporting capabilities.',
    solution: 'Developed a cross-platform activity detection system that monitors idle time and application usage, with a comprehensive dashboard for viewing logs, generating reports, and analyzing productivity metrics.',
    keyFeatures: [
      'Idle time detection and tracking',
      'Application usage monitoring',
      'Comprehensive activity logs',
      'Real-time dashboard with analytics',
      'Customizable reporting and exports',
      'Privacy-focused implementation',
    ],
    results: 'Provided organizations with valuable insights into employee activity patterns while maintaining a balance between monitoring and privacy.',
    screenshots: [
      '/images/activity-1.jpg',
      '/images/activity-2.jpg',
      '/images/activity-3.jpg',
    ],
  },
]

export const projectCategories = ['All', 'Web', 'Mobile', 'Backend', 'UI', 'Automation']
